{% set version = "2022-4.30" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcgmin
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rcgmin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rcgmin/Rcgmin_{{ version }}.tar.gz
  sha256: 2684b8e7fb970da2afbc00e482031cf4447416249d04c4c1740400ad112fb911

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-optextras
  run:
    - r-base
    - r-optextras

test:
  commands:
    - $R -e "library('Rcgmin')"           # [not win]
    - "\"%R%\" -e \"library('Rcgmin')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Rcgmin
  license: GPL-2.0-or-later
  summary: Conjugate gradient minimization of nonlinear functions with box constraints incorporating the Dai/Yuan update. This implementation should be used in place of the "CG" algorithm of the optim() function.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
