appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: mrGxUbJvHSPI7aBZXgdntKTTQ6/1bnKfRkSzlFBUo9E+2EcFTkrT8nt5rj/Gu9hyYub5Ps6hOtfemBJC6+ecvfrTglNYkMz4K9xvFeVFGO+SK6cRqdcuilt2YDe+fiKUw8PXnOz8OX9pN/nBf6zekQXhi60DxspOMnDmRYFnbqaiR9ibkykAIho7q7aWbFKZOuNGiwjp0j/VplG3K6pDhia/v4mGqXE3uxZko/13dfK5iF5WBhQL4TIR1rvIrnK6LNKYQh5tFauSAUDuWAnGX4nADuHNhA2htyCi6449/tSTA82zDDsPnYbBoJPz0Td9LIGy9vXioSHmF/RBJK4sppzEOFi0h97SvUHIpBJf6LAUFDuRAlO3iqMVoKUvVhsZU/O3uhBDAHNVl9JbyDhgOqLfKUdc5Gaz+hT2lpw/hr1xJVB8qmxVTptF9DGs8ETFNOrZyr7qle9eDxLm+t750LjlPoFAAt4v5KGAav+Ge7nFCA6S/OHJJUyDtoR2ZlqbX90MPvj7sFnASjroJDhZzK9msWzJLqGS1Nrs6DsXaeFcpKR3B5UIVZ3f5iuz73s4NlSlyZqR6NKTsqUc+eE7pmktv9E4LmisQ4mLlaA9+9eL0Pk3dKRGVA/LwpF3u0595/iHW0UmS7anbcSed8d613KLEZw3RJpbgS9RvKdSafU=
conda_forge_output_validation: true
