travis:
  secure:
    BINSTAR_TOKEN: RWCu6o1IM3tmsqAAuIeSwCiRP8ALH1emwcdXnoBol1SfGkzYaDeDhVOLMoCbv2OBp7V43jxJy7iyGqpvOt0srKIT9l43mCBPS2XogT/+uex6DiqQ4VxTlN7PxsnZrONmEsyo/Yi+fKLTLOIIZSUVJ8mnMWc6S/w/XomeYU843M7vRfGaMaCNb0R2+3AbMcIXOIdjsDUIXaWAVnBYnEG0yW4PD82g9C0DMAaBXAbOzHQgGW8q28N68O/2CKZksskP0bqwJw51JyVoYNazOh5AdJaTTqUIcmdOyr1WNpbYf3ddzxCpPUG3HEW0Yc5OWkInTeFJ2CkTY3r5DbtBdAkofBmes7N1h7Zmb+fYw0yR6YBJTNEjqfTNmlU9swPD5kCfJ2NR5Ss61Z6zUPjiibB5hpS2F+ZdKzApRU1vQaMvIKDzo5Y0/YyUl0jC5qUrP+07l2NLfRvPlXMBAdtH8HnxQemmY4n8SXCyEqyYM1eHsVHJ++6l4KnmkMpaBzq7z2FIQXvw4OvId6OIEn6pCZ+uxfM50j/itW41vkSzNxe3bbVRICRS6HKYnRxOMPCtDotCr5ceaYChDCWXZTFBX1uJX72NybTLGZSp0xx0kiCkdVQAHgluJHTBbNxJcV3C5mJO67TuSJ8/4i+QsGWI5CNCQmylQvs9peUM7dieWqi9hzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
