travis:
  secure:
    BINSTAR_TOKEN: iykb660uT7bTE/TlwGGB8Giq5SewRUneHibbS75OQzhsDAM9X1QEtue6bNxZjFQIxgns7EwxADHQjZ2oAzpziz9qBPLdPhoSW/YGqzmPd/U52q5HnRU1RMeXwulzO3rA5sqZpridsQc8oABZjW83v4PG67DwM0oXA8SP23X+FVsLteJbzgnXnpGZn0nq8wxBZrjV02hGStYfqW0a6w0Rb4+co6kojohKyShIDPSpVzKGxw/NcqLYi4gfnDaK34tDTqiMJ+4R6OUxrAgAV0GgR79ykYfdTdG0SdIY6NS/m1oL1/x8cqfqtgUtJ5NnPIVsVxj/OYor0K4Gl436Rk6izjEvD6TeH+qeglGL98iwOZ4NwJqYMwp6ih0r3W3SyKy1rA9eh3xwlSgbioVX1m9q2lAUgEEt+wJ97hzJ/3ombhgHvrKidPLStAV6rzwfTqyM6qrRgQ6jkh4Y1ZiID3btzGaNTMl6tsQ2r2JGRhdHM/nHXtWVCDTSuKlhiA/s5NT+V7+C3IlwkgnJVG1W03bXJWLbTuAcN5GopjN5EoVwPcwymTlH4zOcb78MMxNbje5DbdTqdV12YUVNjg/6552lT4nPzSo6d84tHSZ40tbr6VoN5fOE3L3N+C4t0SO3IhNKxyxilrSBl5CfAGVYr0LUsi4zHVoYpnmTVduZQPRF5l8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
